language: java

jdk: oraclejdk8

services:
  - mysql

env:
  - TZ=Europe/Berlin

before_install:
  - mysql -e 'CREATE DATABASE newsboard'
  - mysql newsboard < src/main/resources/sql/create_script.sql
  - mysql newsboard < src/main/resources/sql/example_data.sql

addons:
  sonarqube:
    organization: "mrm1st3r-github"
    branches:
      - master

install: mvn install -Dskip.unitTests=true -Dskip.integrationTests=true -Dmaven.javadoc.skip=true
script: mvn verify sonar:sonar -Dspring.profiles.active=travis -Dskip.unitTests=true -Duser.timezone=Europe/Berlin -Dsonar.language=java
