language: java

jdk: oraclejdk8

services:
  - mysql

env:
  - TZ=Europe/Berlin

before_install:
  - mysql -e 'CREATE DATABASE newsboard'
  - mysql newsboard < src/main/resources/sql/create_script.sql
  - mysql newsboard < src/main/resources/sql/example_data.sql

addons:
  sonarqube:
    organization: "mrm1st3r-github"
    branches:
      - master

jobs:
  include:
    - stage: Unit Test
      script: mvn test -Dmaven.javadoc.skip=true -Duser.timezone=Europe/Berlin
    - stage: Integration Test
      script: mvn integration-test -Dspring.profiles.active=travis -Dskip.unitTests=true -Duser.timezone=Europe/Berlin
    - stage: Code Analysis
      script: mvn sonar:sonar -Dsonar.language=java
