language: java

jdk: oraclejdk8

services:
  - mysql

env:
  - TZ=Europe/Berlin

before_install:
  - mysql -e 'CREATE DATABASE newsboard'
  - mysql newsboard < src/main/resources/sql/create_script.sql
  - mysql newsboard < src/main/resources/sql/example_data.sql

addons:
  sonarqube:
    organization: "mrm1st3r-github"
    branches:
      - develop

script: mvn test sonar:sonar -Dmaven.javadoc.skip=true -Dspring.profiles.active=travis -Duser.timezone=Europe/Berlin -Dsonar.language=java
